services:
    maria-db:
        image: mariadb:11.2.2
        restart: unless-stopped
        environment:
            MARIADB_USER: mariadb-user
            MARIADB_DATABASE: sample
            MARIADB_PASSWORD: mariadb-password
            MARIADB_ROOT_PASSWORD: mariadb-root-password
    mysql-db:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_USER: mysql-user
            MYSQL_PASSWORD: mysql-password
            MYSQL_DATABASE: sample
            MYSQL_ROOT_PASSWORD: mysql-root-password
    postgres-db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: example
    postgis-db:
        image: postgis/postgis
        restart: unless-stopped
        environment:
            POSTGRES_USER: test-user
            POSTGRES_PASSWORD: mypassword
